services:
  rustdesk-api-server-pro:
    container_name: rustdesk-api-server-pro
    image: ghcr.io/lantongxue/rustdesk-api-server-pro:latest
    environment:
      - "ADMIN_USER=admin" # optional
      - "ADMIN_PASS=Waqaf1234" # optional
    volumes:
      - ./server.yaml:/app/server.yaml
    restart: unless-stopped
